apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-order-deployment
spec:
  replicas: 2 # Orchestration: Menjalankan 2 instance server secara otomatis untuk load balancing
  selector:
    matchLabels:
      app: web-order
  template:
    metadata:
      labels:
        app: web-order
    spec:
      containers:
      - name: web-order-container
        image: username_docker_kamu/web-order:latest # Nanti diisi otomatis oleh CI/CD
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-order-service
spec:
  type: LoadBalancer # Mengizinkan akses dari internet (Cloud)
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: web-order